### ISSUE TITLE
static references for pygtk still exist?

### ISSUE THREAD

**Issue by GleLa** [ndf-zz/metarace#1]
Attempting to use Python3

after merging updates - apploader.py still has references to pygtk.  

Traceback (most recent call last):
  File "metarace", line 20, in <module>
    from metarace import apploader
  File "/home/user2/.local/lib/python3.8/site-packages/metarace/apploader.py", line 20, in <module>
    import pygtk
ModuleNotFoundError: No module named 'pygtk'

**Comment by ndf-zz** [comment]
Hi, thanks and sorry this project is still very much pre-alpha, only the packages included in this repo have been updated from v1.
